spring.application.name=inventario
server.port=${SERVER_PORT:8080}

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/linktictest}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:0826}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# springdoc-openapi Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# variable
productosEndpoint=${PRODUCTOS_API_URL:http://localhost:8081/api/productos}

# Api Token
apiToken=${API_SECURITY_TOKEN:IJSKLs548dojklsfuxna884suzxHSU}